version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/python3.8
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python testscript_cli.py
          name: TestDLC

workflows:
  main:
    jobs:
      - build-and-test
